version: "3"
services:
  node-app:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=8081
    # env_file:
    #   - ./.env
